# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 15:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buiness',
            fields=[
                ('num', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('call', models.CharField(max_length=20)),
                ('rem', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('momey', models.CharField(max_length=10)),
                ('Buiness', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toorder.Buiness')),
            ],
        ),
    ]
