# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 05:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toorder', '0002_auto_20170731_0515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buiness',
            name='name',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='buiness',
            name='num',
            field=models.CharField(max_length=20),
        ),
    ]
