# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toorder', '0004_auto_20170731_0607'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper', models.CharField(max_length=20)),
                ('sq', models.TextField(null=True)),
                ('money', models.CharField(max_length=20)),
            ],
        ),
    ]
